# Generated by Django 3.1.2 on 2020-10-27 15:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0002_remove_slot_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='tables',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), default=[], size=8),
        ),
    ]
