# Generated by Django 3.1.2 on 2020-10-27 15:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0004_auto_20201027_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='status',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='tables',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, size=8),
        ),
    ]
