# Generated by Django 3.1.2 on 2020-10-27 15:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0005_auto_20201027_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='tables',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, size=8),
        ),
    ]
