# Generated by Django 3.1.2 on 2020-10-27 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20201022_2154'),
        ('slots', '0006_auto_20201027_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='book_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book'),
        ),
    ]
