# Generated by Django 3.1.2 on 2020-10-27 21:48

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20201022_2154'),
        ('slots', '0008_auto_20201027_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='book_id',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='slots', to='books.book'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='tables',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=[], size=None),
        ),
    ]
