# Generated by Django 3.1.2 on 2020-10-27 21:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0009_auto_20201027_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='tables',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=list, size=None),
        ),
    ]
