# Generated by Django 3.1.2 on 2020-10-27 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_auto_20201022_2210'),
        ('books', '0002_auto_20201022_2154'),
        ('slots', '0010_auto_20201027_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='book_id',
        ),
        migrations.AddField(
            model_name='slot',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='slots', to='books.book'),
        ),
        migrations.AddField(
            model_name='slot',
            name='guest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='guest', to='guests.guest'),
        ),
    ]
