# Generated by Django 3.1.2 on 2020-11-09 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_remove_guest_slots'),
        ('slots', '0012_slot_reservation_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='guest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='slots', to='guests.guest'),
        ),
    ]
