# Generated by Django 3.1.2 on 2020-10-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.TextField(default='two-top-horizontal')),
                ('position_left', models.TextField(default='0px')),
                ('position_top', models.TextField(default='0px')),
                ('name', models.TextField(default='1')),
                ('restaurant_id', models.IntegerField(default=1)),
            ],
        ),
    ]
