# Generated by Django 3.1.2 on 2020-10-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='reservation_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='status',
            field=models.TextField(blank=True),
        ),
    ]
