# Generated by Django 3.1.2 on 2020-10-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(default='', max_length=50)),
                ('last_name', models.TextField(default='', max_length=50)),
                ('phone_number', models.IntegerField(default='')),
                ('guest_notes', models.TextField(default='')),
                ('root_user', models.BooleanField(default=False)),
            ],
        ),
    ]
