# Generated by Django 3.1.2 on 2020-10-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_auto_20201022_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='first_name',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='guest',
            name='guest_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='guest',
            name='last_name',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone_number',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='guest',
            name='root_user',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
