# Generated by Django 3.1.2 on 2020-11-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_guest_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='slots',
        ),
    ]
