# Generated by Django 3.1.2 on 2020-11-09 17:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_remove_guest_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='slot',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=list, size=None),
        ),
    ]
